
export interface ICustomerDto {

    userID: string
    fiscalYear: number
    monthIndex: number
    custID: number
    regFiscalYear?: number
    regMonthIndex?: number
    customerName: string
    Ketena: string
    kebele: string
    houseNo: string
    village: string
    telephone: string
    mobile: string
    bookNo: string
    accountNo: string
    contractNo: string
    ordinaryNo?: number
    custCategoryCode: string
    meterno: string
    meterSizeCode: string
    meterType: string
    meterDigit: number
    meterCountryOrigin: string
    meterModel: string
    installationDate?: Date
    meterStartReading: number
    meterAltitude?: number
    meterLongitude?: number
    sdPaid: string
     meterClass: string
    materSource: string
    meterStatus: string
    regDate: Date
    waterSource:string
    readerName: string
    paymentPlace: string
    paymentDuration: string
    paymentMode: string
    billSalesGroup: string
    onlineGroup: string
    bankCode: string
    bankAccount: string
    trasnferBY: string
    billOfficerId: string
    transferMI?: number
    transferDT: string
    field01: string
    field02: string
    field03: number
    field04?: number
    enterBy: string
    enterDate?: Date
    modifyBy: string
    modifyDate: Date
    dataSynched: string
}